apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpweb-deployment
spec:
  replicas: 3 # tells deployment to run 3 pods matching the template
  selector:
    matchLabels:
      app: wpweb-deploy-app
  template:
    metadata:
      labels:
        app: wpweb-deploy-app
    spec:
      containers:
      - name: wpweb-deploy-pod
        image: praveenprabha/my_wordpress:v2
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: 192.168.10.106
        - name: DB_NAME
          value: wpdb
        - name: DB_USER
          value: wpuser
        - name: DB_PASSWORD
          value: wppass_789
        - name: MEMCAHED_HOST
          value: 192.168.49.240
