apiVersion: v1
kind: PersistentVolume
metadata:
  name: wpdb-pv-1gb
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpdb-pvc-1gb
  labels:
    app: wpdb-pvc-1gb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
